/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AutomationRouteImport } from './routes/automation'
import { Route as GeekettappRouteImport } from './routes/geekettapp'
import { Route as LabRouteImport } from './routes/lab'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as ProjectBriefRouteImport } from './routes/project-brief'
import { Route as ShopRouteImport } from './routes/shop'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationRoute = AutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => rootRouteImport,
} as any)
const GeekettappRoute = GeekettappRouteImport.update({
  id: '/geekettapp',
  path: '/geekettapp',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectBriefRoute = ProjectBriefRouteImport.update({
  id: '/project-brief',
  path: '/project-brief',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/automation': typeof AutomationRoute
  '/geekettapp': typeof GeekettappRoute
  '/lab': typeof LabRoute
  '/plan': typeof PlanRoute
  '/project-brief': typeof ProjectBriefRoute
  '/shop': typeof ShopRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/automation': typeof AutomationRoute
  '/geekettapp': typeof GeekettappRoute
  '/lab': typeof LabRoute
  '/plan': typeof PlanRoute
  '/project-brief': typeof ProjectBriefRoute
  '/shop': typeof ShopRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/automation': typeof AutomationRoute
  '/geekettapp': typeof GeekettappRoute
  '/lab': typeof LabRoute
  '/plan': typeof PlanRoute
  '/project-brief': typeof ProjectBriefRoute
  '/shop': typeof ShopRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/automation'
    | '/geekettapp'
    | '/lab'
    | '/plan'
    | '/project-brief'
    | '/shop'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/automation'
    | '/geekettapp'
    | '/lab'
    | '/plan'
    | '/project-brief'
    | '/shop'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/automation'
    | '/geekettapp'
    | '/lab'
    | '/plan'
    | '/project-brief'
    | '/shop'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AutomationRoute: typeof AutomationRoute
  GeekettappRoute: typeof GeekettappRoute
  LabRoute: typeof LabRoute
  PlanRoute: typeof PlanRoute
  ProjectBriefRoute: typeof ProjectBriefRoute
  ShopRoute: typeof ShopRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation': {
      id: '/automation'
      path: '/automation'
      fullPath: '/automation'
      preLoaderRoute: typeof AutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geekettapp': {
      id: '/geekettapp'
      path: '/geekettapp'
      fullPath: '/geekettapp'
      preLoaderRoute: typeof GeekettappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project-brief': {
      id: '/project-brief'
      path: '/project-brief'
      fullPath: '/project-brief'
      preLoaderRoute: typeof ProjectBriefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AutomationRoute: AutomationRoute,
  GeekettappRoute: GeekettappRoute,
  LabRoute: LabRoute,
  PlanRoute: PlanRoute,
  ProjectBriefRoute: ProjectBriefRoute,
  ShopRoute: ShopRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
